language: python
python:
  - "3.6"
  - "3.5"


install:
   - pip install -r requirements.txt
env:
  - FLASK_APP=run.py
  - ENV="testing"
  - SECRET_KEY="ndvbfsdjmnbfjkmnbdcbnmxvjhnmbsxnmbasdjnmmdsnmxbjhdshjcknmb"

script:
  nosetests --with-coverage --cover-package=app/ && coverage report
after_success:
  coveralls