anguage: python
python:
  - "3.6"
  - "3.5"


install:
   - pip install -r requirements.txt
script:
  nosetests --with-coverage --cover-package=app/controllers && coverage report
after_success:
  coveralls