"""empty message

Revision ID: 030129437aa6
Revises: 
Create Date: 2017-07-20 23:20:51.781005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030129437aa6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bucket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('privacy', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bucket')
    # ### end Alembic commands ###
