"""empty message

Revision ID: 552664adda5c
Revises: bea1ddca950c
Create Date: 2017-08-15 05:16:27.126936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '552664adda5c'
down_revision = 'bea1ddca950c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('bucket_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'activities', 'buckets', ['bucket_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_column('activities', 'bucket_id')
    # ### end Alembic commands ###
